Fixed bot failure after d20bf5a7258d4b6a7
There were some bot failures due unused funtion `rotateSign`
left in code.

http://lab.llvm.org:8011/builders/clang-ppc64le-rhel/builds/3731

error: unused function 'rotateSign' [-Werror,-Wunused-function]
static uint64_t rotateSign(int64_t I)

llvm-monorepo: a0d847c6cdcbe167213d91313577c57073d5c013