Temporarily revert "SafepointIRVerifier port to new Pass Manager" to unbreak the modular bots and its follow-up commit.
This reverts commit https://reviews.llvm.org/D59825
because it introduced a

fatal error: cyclic dependency in module 'LLVM_intrinsic_gen': LLVM_intrinsic_gen -> LLVM_IR -> LLVM_intrinsic_gen

llvm-svn: 357201

llvm-monorepo: 119fdeded82a0150e16db96179b339eae653741f