[AMDGPU] Avoid unused variable warning in Release builds. NFC.
SIRegisterInfo.cpp:480:19: error: unused variable 'SOffset'

llvm-monorepo: b777d3049652746881b74152416e3ffb025a887c